### PR TITLE
Add thumbnails to the README.md

### PR DESCRIPTION
**Pull request by william76**
Added a HTML table to render thumbnails of the logos with hyperlinks.

### CODE REVIEW

**Comment by william76** [comment]
@mhoemmen I modified the README.md file a little to add thumbnails of the images so it gets rendered in github.

**Comment by mhoemmen** [comment]
Woah, didn't we want to merge into trilinos:develop first?

**Comment by maherou** [comment]
There were no failing tests, so I pushed directly to master :)

**Comment by mhoemmen** [comment]
@maherou fine :)

**Pull request merged**
